import { test, expect } from "@playwright/test";
import { restoreSnapshot } from "../../framework/api/environment.api";
import { loginAs } from "../../framework/auth/auth.service";
import { users } from "../../framework/auth/users";

test("test", async ({ page, request }) => {
  await restoreSnapshot(request);
  await loginAs(page, users.rahbar);
  await page.getByRole("button", { name: "Navigation" }).click();
  await page.getByText("تست وب جدید").click();
  await page.getByText("تنظیمات مرتب سازی گزارشات").click();
  await page.getByRole('button', { name: 'تنظیمات' }).click();
  await page.getByText("مرتب سازی", { exact: true }).click();
  await page.locator("#fd-select-0 fd-icon").click();
  await page.getByRole("option", { name: "نام" }).locator("span").click();
  await page.locator("fd-popover-control div span fd-icon").nth(2).click();
  await page.getByText("صعودی").click();
  await page.getByRole("button", { name: "تایید" }).click();
  await expect(page.locator('bsu-ui-table-view')).toContainText('نام سن ‫تست 1‬‫‪3‬‫تست 1‬‫‪1‬‫تست 2‬‫‪2‬‫تست 2.1‬‫‪2‬');
  await page.getByRole('button', { name: 'تنظیمات' }).click();
  await page.getByText("مرتب سازی", { exact: true }).click();
  await page.locator('button[glyph="sys-cancel"]').click();
  await page.locator('fd-icon.sap-icon--slim-arrow-down').nth(3).click();
  await page.getByRole("option", { name: "سن" }).locator("span").click();
  await page.getByTitle(" ", { exact: true }).locator("fd-icon").last().click();
  await page.getByRole("option", { name: "نزولی" }).click();
  await page.getByRole("button", { name: "تایید" }).click();
  await expect(page.locator('bsu-ui-table-view')).toContainText('نام سن ‫تست 1‬‫‪3‬‫تست 2‬‫‪2‬‫تست 2.1‬‫‪2‬‫تست 1‬‫‪1‬');
  await page.getByRole('button', { name: 'تنظیمات' }).click();
  await page.getByText("مرتب سازی", { exact: true }).click();
  await page.locator('button[glyph="sys-cancel"]').click();
  await page.locator('fd-icon.sap-icon--slim-arrow-down').nth(3).click();
  await page.getByRole("option", { name: "سن" }).locator("span").click();
  await page.getByTitle(" ", { exact: true }).locator("fd-icon").last().click();
  await page.getByText("صعودی").click();
  await page.locator('button[glyph="add"]').click();
  await page.locator('span:has(.sap-icon--slim-arrow-down)').nth(2).click();
  await page.getByRole("option", { name: "نام" }).locator("span").click();
  await page.locator('span:has(.sap-icon--slim-arrow-down)').nth(3).click();
  await page.getByText("نزولی").click();
  await page.getByRole("button", { name: "تایید" }).click();
  await page.getByRole('button', { name: 'تنظیمات' }).click();
  await page.getByText("مرتب سازی", { exact: true }).click();
  await page.getByRole("button", { name: "تنظیم مجدد" }).click();
  await expect(page.locator('bsu-ui-grid-sort-setting')).toContainText('');
  await page.getByRole("button", { name: "تایید" }).click();
});
